//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navferty.ExcelAddIn.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Navferty.ExcelAddIn.Web.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select only one row to insert!.
        /// </summary>
        internal static string CurrencyExchangeRates_Error_CanSelectOnlyOneRow {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_CanSelectOnlyOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a cell in the table!.
        /// </summary>
        internal static string CurrencyExchangeRates_Error_NedAnyCellSelection {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_NedAnyCellSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data from online source due to network error!.
        /// </summary>
        internal static string CurrencyExchangeRates_Error_Network {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, currently does not provide data for {1}!
        ///
        ///Please try again later, or specify a different date..
        /// </summary>
        internal static string CurrencyExchangeRates_Error_NotAvailYet {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_NotAvailYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse data from online source due to data format error!.
        /// </summary>
        internal static string CurrencyExchangeRates_Error_ParseError {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by currency name and code.
        /// </summary>
        internal static string CurrencyExchangeRates_FilterDescription {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Filter:.
        /// </summary>
        internal static string CurrencyExchangeRates_FilterTitle {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rates.
        /// </summary>
        internal static string CurrencyExchangeRates_FormTitle {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string CurrencyExchangeRates_GridColumn_ISO {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_GridColumn_ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyExchangeRates_GridColumn_Name {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_GridColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        internal static string CurrencyExchangeRates_GridColumn_Rate {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_GridColumn_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Into Worksheet Cell.
        /// </summary>
        internal static string CurrencyExchangeRates_PasteToCell {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_PasteToCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source:.
        /// </summary>
        internal static string CurrencyExchangeRates_Source {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Bank of the Russian Federation (Bank of Russia).
        /// </summary>
        internal static string CurrencyExchangeRates_Sources_CBRF {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Sources_CBRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Central Bank.
        /// </summary>
        internal static string CurrencyExchangeRates_Sources_ECB {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Sources_ECB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Bank of Ukraine.
        /// </summary>
        internal static string CurrencyExchangeRates_Sources_NBU {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Sources_NBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0} units.
        /// </summary>
        internal static string CurrencyExchangeRates_UnitsFormat {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_UnitsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
