//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavfertyExcelAddIn.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavfertyExcelAddIn.Localization.RibbonLabels", typeof(RibbonLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commons.
        /// </summary>
        internal static string CommonGroup {
            get {
                return ResourceManager.GetString("CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Values.
        /// </summary>
        internal static string ConvertingValues {
            get {
                return ResourceManager.GetString("ConvertingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown.
        /// </summary>
        internal static string CopyAsMarkdown {
            get {
                return ResourceManager.GetString("CopyAsMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML from XSD.
        /// </summary>
        internal static string CreateSampleXml {
            get {
                return ResourceManager.GetString("CreateSampleXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates.
        /// </summary>
        internal static string CurrencyExchangeRatesSelect {
            get {
                return ResourceManager.GetString("CurrencyExchangeRatesSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Names.
        /// </summary>
        internal static string CutNames {
            get {
                return ResourceManager.GetString("CutNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Errors.
        /// </summary>
        internal static string FindErrors {
            get {
                return ResourceManager.GetString("FindErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Values.
        /// </summary>
        internal static string FormattingValues {
            get {
                return ResourceManager.GetString("FormattingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize Duplicates.
        /// </summary>
        internal static string HighlightDuplicates {
            get {
                return ResourceManager.GetString("HighlightDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Numeric.
        /// </summary>
        internal static string ParseNumerics {
            get {
                return ResourceManager.GetString("ParseNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets Protection.
        /// </summary>
        internal static string ProtectUnprotectWorksheets {
            get {
                return ResourceManager.GetString("ProtectUnprotectWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Spaces.
        /// </summary>
        internal static string RemoveAllSpaces {
            get {
                return ResourceManager.GetString("RemoveAllSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        internal static string RepairConditionalFormat {
            get {
                return ResourceManager.GetString("RepairConditionalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Chars &apos;У&apos; -&gt; &apos;Y&apos;.
        /// </summary>
        internal static string ReplaceChars {
            get {
                return ResourceManager.GetString("ReplaceChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data protection.
        /// </summary>
        internal static string SecurityGroup {
            get {
                return ResourceManager.GetString("SecurityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stringify Numerics.
        /// </summary>
        internal static string StringifyNumericsButton {
            get {
                return ResourceManager.GetString("StringifyNumericsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...to English.
        /// </summary>
        internal static string StringifyNumericsEn {
            get {
                return ResourceManager.GetString("StringifyNumericsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...to French.
        /// </summary>
        internal static string StringifyNumericsFr {
            get {
                return ResourceManager.GetString("StringifyNumericsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...to Russian.
        /// </summary>
        internal static string StringifyNumericsRu {
            get {
                return ResourceManager.GetString("StringifyNumericsRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Style (A1/R1C1).
        /// </summary>
        internal static string SwitchReferenceStyle {
            get {
                return ResourceManager.GetString("SwitchReferenceStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Case.
        /// </summary>
        internal static string ToggleCase {
            get {
                return ResourceManager.GetString("ToggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Tabs.
        /// </summary>
        internal static string ToggleSheetLabels {
            get {
                return ResourceManager.GetString("ToggleSheetLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Transliteration &apos;У&apos; -&gt; &apos;U&apos;.
        /// </summary>
        internal static string Transliterate {
            get {
                return ResourceManager.GetString("Transliterate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string TransliterateButton {
            get {
                return ResourceManager.GetString("TransliterateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Extra Spaces.
        /// </summary>
        internal static string TrimExtraSpaces {
            get {
                return ResourceManager.GetString("TrimExtraSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Spaces.
        /// </summary>
        internal static string TrimSpaces {
            get {
                return ResourceManager.GetString("TrimSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Text.
        /// </summary>
        internal static string TrimTextByLength {
            get {
                return ResourceManager.GetString("TrimTextByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Last Action.
        /// </summary>
        internal static string UndoLastAction {
            get {
                return ResourceManager.GetString("UndoLastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmerge.
        /// </summary>
        internal static string UnmergeCells {
            get {
                return ResourceManager.GetString("UnmergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File Protection.
        /// </summary>
        internal static string UnprotectWorkbook {
            get {
                return ResourceManager.GetString("UnprotectWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string ValidateValuesButton {
            get {
                return ResourceManager.GetString("ValidateValuesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ValidateValuesDate {
            get {
                return ResourceManager.GetString("ValidateValuesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerics.
        /// </summary>
        internal static string ValidateValuesNumerics {
            get {
                return ResourceManager.GetString("ValidateValuesNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian TIN (Organization).
        /// </summary>
        internal static string ValidateValuesTinOrganization {
            get {
                return ResourceManager.GetString("ValidateValuesTinOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian TIN (Personal).
        /// </summary>
        internal static string ValidateValuesTinPersonal {
            get {
                return ResourceManager.GetString("ValidateValuesTinPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Contents Text.
        /// </summary>
        internal static string ValidateValuesXml {
            get {
                return ResourceManager.GetString("ValidateValuesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate XML with XSD.
        /// </summary>
        internal static string ValidateXml {
            get {
                return ResourceManager.GetString("ValidateXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewGroup {
            get {
                return ResourceManager.GetString("ViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web tools.
        /// </summary>
        internal static string WebToolsGroup {
            get {
                return ResourceManager.GetString("WebToolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Tools.
        /// </summary>
        internal static string XmlToolsGroup {
            get {
                return ResourceManager.GetString("XmlToolsGroup", resourceCulture);
            }
        }
    }
}
