//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavfertyExcelAddIn.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavfertyExcelAddIn.Localization.RibbonLabels", typeof(RibbonLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commons.
        /// </summary>
        internal static string CommonGroup {
            get {
                return ResourceManager.GetString("CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converting Values.
        /// </summary>
        internal static string ConvertingValues {
            get {
                return ResourceManager.GetString("ConvertingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy as Markdown.
        /// </summary>
        internal static string CopyAsMarkdown {
            get {
                return ResourceManager.GetString("CopyAsMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Sample XML based on XSD.
        /// </summary>
        internal static string CreateSampleXml {
            get {
                return ResourceManager.GetString("CreateSampleXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut Names.
        /// </summary>
        internal static string CutNames {
            get {
                return ResourceManager.GetString("CutNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find Formula Errors on Current Sheet.
        /// </summary>
        internal static string FindErrors {
            get {
                return ResourceManager.GetString("FindErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formatting Values.
        /// </summary>
        internal static string FormattingValues {
            get {
                return ResourceManager.GetString("FormattingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highlight Duplicates.
        /// </summary>
        internal static string HighlightDuplicates {
            get {
                return ResourceManager.GetString("HighlightDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parse Numerics.
        /// </summary>
        internal static string ParseNumerics {
            get {
                return ResourceManager.GetString("ParseNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Chars &apos;У&apos; -&gt; &apos;Y&apos;.
        /// </summary>
        internal static string ReplaceChars {
            get {
                return ResourceManager.GetString("ReplaceChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Case.
        /// </summary>
        internal static string StringifyNumericsButton {
            get {
                return ResourceManager.GetString("StringifyNumericsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On English.
        /// </summary>
        internal static string StringifyNumericsEn {
            get {
                return ResourceManager.GetString("StringifyNumericsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On Russian.
        /// </summary>
        internal static string StringifyNumericsRu {
            get {
                return ResourceManager.GetString("StringifyNumericsRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle Case.
        /// </summary>
        internal static string ToggleCase {
            get {
                return ResourceManager.GetString("ToggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliterate &apos;У&apos; -&gt; &apos;U&apos;.
        /// </summary>
        internal static string Transliterate {
            get {
                return ResourceManager.GetString("Transliterate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliterate.
        /// </summary>
        internal static string TransliterateButton {
            get {
                return ResourceManager.GetString("TransliterateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Spaces.
        /// </summary>
        internal static string TrimSpaces {
            get {
                return ResourceManager.GetString("TrimSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unmerge Cells.
        /// </summary>
        internal static string UnmergeCells {
            get {
                return ResourceManager.GetString("UnmergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unprotect Workbook.
        /// </summary>
        internal static string UnprotectWorkbook {
            get {
                return ResourceManager.GetString("UnprotectWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validate Values.
        /// </summary>
        internal static string ValidateValuesButton {
            get {
                return ResourceManager.GetString("ValidateValuesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string ValidateValuesDate {
            get {
                return ResourceManager.GetString("ValidateValuesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numerics.
        /// </summary>
        internal static string ValidateValuesNumerics {
            get {
                return ResourceManager.GetString("ValidateValuesNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian TIN (Organization).
        /// </summary>
        internal static string ValidateValuesTinOrganization {
            get {
                return ResourceManager.GetString("ValidateValuesTinOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian TIN (Personal).
        /// </summary>
        internal static string ValidateValuesTinPersonal {
            get {
                return ResourceManager.GetString("ValidateValuesTinPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML contents text.
        /// </summary>
        internal static string ValidateValuesXml {
            get {
                return ResourceManager.GetString("ValidateValuesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validate XML with XSD.
        /// </summary>
        internal static string ValidateXml {
            get {
                return ResourceManager.GetString("ValidateXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML Tools.
        /// </summary>
        internal static string XmlToolsGroup {
            get {
                return ResourceManager.GetString("XmlToolsGroup", resourceCulture);
            }
        }
    }
}
