//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavfertyExcelAddIn.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonSupertips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonSupertips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavfertyExcelAddIn.Localization.RibbonSupertips", typeof(RibbonSupertips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the selected range of values to the clipboard using Markdown markup..
        /// </summary>
        internal static string CopyAsMarkdown {
            get {
                return ResourceManager.GetString("CopyAsMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the development....
        /// </summary>
        internal static string CutNames {
            get {
                return ResourceManager.GetString("CutNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all cells in the specified range that have any errors (#)..
        /// </summary>
        internal static string FindErrors {
            get {
                return ResourceManager.GetString("FindErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint groups of duplicates with different colors..
        /// </summary>
        internal static string HighlightDuplicates {
            get {
                return ResourceManager.GetString("HighlightDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert the cell data type to a numeric one..
        /// </summary>
        internal static string ParseNumerics {
            get {
                return ResourceManager.GetString("ParseNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all spaces in selected cells or entire sheet.
        /// </summary>
        internal static string RemoveAllSpaces {
            get {
                return ResourceManager.GetString("RemoveAllSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill conditional formatting in entire table, with rules based on first table row.
        /// </summary>
        internal static string RepairConditionalFormat {
            get {
                return ResourceManager.GetString("RepairConditionalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change similar letters of the Russian and English alphabets, for example: &apos;У&apos; - &gt; &apos;Y&apos;..
        /// </summary>
        internal static string ReplaceChars {
            get {
                return ResourceManager.GetString("ReplaceChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the numeric value of the cell with words. The default is the Russian language.
        ///Allows rewriting values in range -999 billion to 999 billion, with precision up to thousandths..
        /// </summary>
        internal static string StringifyNumericsButton {
            get {
                return ResourceManager.GetString("StringifyNumericsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the numeric value of a cell in English with words..
        /// </summary>
        internal static string StringifyNumericsEn {
            get {
                return ResourceManager.GetString("StringifyNumericsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the numeric value of a cell in French with words..
        /// </summary>
        internal static string StringifyNumericsFr {
            get {
                return ResourceManager.GetString("StringifyNumericsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite the numeric value of a cell in Russian with words..
        /// </summary>
        internal static string StringifyNumericsRu {
            get {
                return ResourceManager.GetString("StringifyNumericsRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the case of all words in the cell. Replacement order: lowercase, uppercase, first capital, lowercase....
        /// </summary>
        internal static string ToggleCase {
            get {
                return ResourceManager.GetString("ToggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Russian alphabet to English using transliteration, for example: &apos;У&apos; - &gt; &apos;U&apos;..
        /// </summary>
        internal static string Transliterate {
            get {
                return ResourceManager.GetString("Transliterate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full using transliteration (by default) or partial replacement of the Russian alphabet (by analogy) with English. Example of transliteration: &apos;У&apos; - &gt; &apos;U&apos;, example of substitution by analogy:&apos; У &apos; - &gt; &apos;Y&apos;..
        /// </summary>
        internal static string TransliterateButton {
            get {
                return ResourceManager.GetString("TransliterateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim extra spaces in cell values. Remove all trailing spaces, replace duplicated spaces in the middle of cell values..
        /// </summary>
        internal static string TrimExtraSpaces {
            get {
                return ResourceManager.GetString("TrimExtraSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim or remove spaces, tabs and &apos;new line&apos; symbols..
        /// </summary>
        internal static string TrimSpaces {
            get {
                return ResourceManager.GetString("TrimSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the latest action done with this add-in. The undo is possible for certain functions in the sections &apos;Converting Values&apos; and &apos;Formatting Values&apos; and only in case the cells&apos; values have not been changed after that action..
        /// </summary>
        internal static string UndoLastAction {
            get {
                return ResourceManager.GetString("UndoLastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split merged cells and fill each cell with original content..
        /// </summary>
        internal static string UnmergeCells {
            get {
                return ResourceManager.GetString("UnmergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking values against standards selected with drop down..
        /// </summary>
        internal static string ValidateValuesButton {
            get {
                return ResourceManager.GetString("ValidateValuesButton", resourceCulture);
            }
        }
    }
}
