//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavfertyExcelAddIn.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavfertyExcelAddIn.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unlock workbook contents because of wrong workbook format. Please save workbook as xlsx or xlsm and try again.
        /// </summary>
        internal static string CannotUnlockPleaseSaveAsXml {
            get {
                return ResourceManager.GetString("CannotUnlockPleaseSaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a cell in the table!.
        /// </summary>
        internal static string CurrencyExchangeRates_Error_NedAnyCellSelection {
            get {
                return ResourceManager.GetString("CurrencyExchangeRates_Error_NedAnyCellSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active workbook.
        /// </summary>
        internal static string NoActiveWorkbook {
            get {
                return ResourceManager.GetString("NoActiveWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no errors in range {0}.
        /// </summary>
        internal static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching sheets in the workbook.
        /// </summary>
        internal static string NoMatchingWorkSheets {
            get {
                return ResourceManager.GetString("NoMatchingWorkSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string SheetProtection_Clear {
            get {
                return ResourceManager.GetString("SheetProtection_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string SheetProtection_Execute {
            get {
                return ResourceManager.GetString("SheetProtection_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string SheetProtection_Password {
            get {
                return ResourceManager.GetString("SheetProtection_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password for worksheets (not required)....
        /// </summary>
        internal static string SheetProtection_PasswordBanner {
            get {
                return ResourceManager.GetString("SheetProtection_PasswordBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string SheetProtection_Protected {
            get {
                return ResourceManager.GetString("SheetProtection_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protection for sheets:.
        /// </summary>
        internal static string SheetProtection_ProtectionForSheets {
            get {
                return ResourceManager.GetString("SheetProtection_ProtectionForSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SheetProtection_Set {
            get {
                return ResourceManager.GetString("SheetProtection_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contents.
        /// </summary>
        internal static string SheetProtectionFlag_Contents {
            get {
                return ResourceManager.GetString("SheetProtectionFlag_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shapes.
        /// </summary>
        internal static string SheetProtectionFlag_DrawingObjects {
            get {
                return ResourceManager.GetString("SheetProtectionFlag_DrawingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scenarios.
        /// </summary>
        internal static string SheetProtectionFlag_Scenarios {
            get {
                return ResourceManager.GetString("SheetProtectionFlag_Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user interface.
        /// </summary>
        internal static string SheetProtectionFlag_UI {
            get {
                return ResourceManager.GetString("SheetProtectionFlag_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navferty Excle add-in. Published under MIT licence. Version .
        /// </summary>
        internal static string ShowVersionMessage {
            get {
                return ResourceManager.GetString("ShowVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite Export Options.
        /// </summary>
        internal static string SqliteExport_OptionsTitle {
            get {
                return ResourceManager.GetString("SqliteExport_OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to skip:.
        /// </summary>
        internal static string SqliteExport_RowsToSkip {
            get {
                return ResourceManager.GetString("SqliteExport_RowsToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use first row as column names.
        /// </summary>
        internal static string SqliteExport_UseFirstRowAsHeaders {
            get {
                return ResourceManager.GetString("SqliteExport_UseFirstRowAsHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting to SQLite.
        /// </summary>
        internal static string SqliteExportError {
            get {
                return ResourceManager.GetString("SqliteExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook successfully exported to SQLite database.
        /// </summary>
        internal static string SqliteExportSuccess {
            get {
                return ResourceManager.GetString("SqliteExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully validated, no errors or warnings detected.
        /// </summary>
        internal static string SuccessfullyValidatedMessage {
            get {
                return ResourceManager.GetString("SuccessfullyValidatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unsaved changes will be lost. Active workbook may become corrupted. It is strongly recommended to create backup. Continue?.
        /// </summary>
        internal static string UnsavedChangesWillBeLostPrompt {
            get {
                return ResourceManager.GetString("UnsavedChangesWillBeLostPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA project unprotected. To enable viewing source code go to VBA project properties in VBE editor, tab Protection, set any password and press OK. Then you can disable password by unchecking the option Lock project for viewing..
        /// </summary>
        internal static string VbaUnprotected {
            get {
                return ResourceManager.GetString("VbaUnprotected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook &apos;{0}&apos; have no worksheets!.
        /// </summary>
        internal static string WorkSheetsNotFound {
            get {
                return ResourceManager.GetString("WorkSheetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet Name.
        /// </summary>
        internal static string WsName {
            get {
                return ResourceManager.GetString("WsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string XmlValidationReport_ElementName {
            get {
                return ResourceManager.GetString("XmlValidationReport_ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string XmlValidationReport_Message {
            get {
                return ResourceManager.GetString("XmlValidationReport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string XmlValidationReport_Severity {
            get {
                return ResourceManager.GetString("XmlValidationReport_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string XmlValidationReport_Value {
            get {
                return ResourceManager.GetString("XmlValidationReport_Value", resourceCulture);
            }
        }
    }
}
